version: '3.8'

services:

  db:
    image: 'mysql:8.0'
    container_name: db
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_DATABASE: user
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
#    networks:
#      - profile-service-network

  reactive-mysql-service:
    image: reactive-mysql-service
    hostname: reactive-mysql-service
    build:
      context: ../reactive-mysql
      dockerfile: Dockerfile
    ports:
      - "8888:8080"
    restart: always
#    networks:
#      - profile-service-network
