spring:
  r2dbc:
    username: root
    password: root
    url: r2dbc:pool:mysql://localhost:3306/user
  liquibase:
    change-log: classpath:db/changelog-master.xml
    url: jdbc:mysql://localhost:3306/user
    user: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  mail:
    host: smtp.gmail.com
    port: 465
    username: changeme
    password: changeme
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
  profiles:
    active: local
logging:
  level:
    org:
      springframework:
        data:
          r2dbc: DEBUG

